version: "3.3"

services:
  postgres_db:
    container_name: taskmanager_db
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-c", "max_connections=200"]
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - taskmanagerdb:/var/lib/postgresql/data
    networks:
      - taskmanager_network

volumes:
  taskmanagerdb:
    driver: local

networks:
  taskmanager_network:
    driver: bridge