// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type List struct {
	ID        uuid.UUID      `json:"id"`
	Name      sql.NullString `json:"name"`
	Type      string         `json:"type"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type ListUser struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	ListID    uuid.NullUUID `json:"list_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Note struct {
	ID        uuid.UUID      `json:"id"`
	ListID    uuid.UUID      `json:"list_id"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	Reminder  sql.NullTime   `json:"reminder"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Task struct {
	ID          uuid.UUID      `json:"id"`
	ListID      uuid.UUID      `json:"list_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Tag         sql.NullString `json:"tag"`
	Priority    string         `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	HashPassword string       `json:"hash_password"`
}
