// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateListUser(ctx context.Context, arg CreateListUserParams) (ListUser, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetList(ctx context.Context, id uuid.UUID) (List, error)
	GetListUser(ctx context.Context, id uuid.UUID) (ListUser, error)
	GetNote(ctx context.Context, id uuid.UUID) (Note, error)
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListList(ctx context.Context, arg ListListParams) ([]List, error)
	ListListUser(ctx context.Context, arg ListListUserParams) ([]List, error)
	ListNote(ctx context.Context, arg ListNoteParams) ([]Note, error)
	ListTask(ctx context.Context, arg ListTaskParams) ([]Task, error)
}

var _ Querier = (*Queries)(nil)
